### ISSUE TITLE
Certains éléments restent clairs à l'écran en thème sombre

### ISSUE THREAD

**Issue by jd-develop** [DocSystem/pronotetools#2]
Bonjour !
Je viens d'installer Pronotetools pour Firefox (Firefox 92.0 64bits sur Windows 10 20H2), mais certains éléments ne s'affichent pas correctement... (ci-joint captures d'écran)

Explication des captures d'écran :
1° Les autres paramètres s'affichent en clair
2° et 3° Sections entières s'affichant en clair
4° et 5° Mauvais contraste

En espérant voir une mise à jour arriver afin de corriger cela.
Bonne journée ! 😁 
Jean Dubois

PS : Je laisserai un commentaire à cette issue si jamais je trouve d'autres problèmes.

![pronotetools3](https://user-images.githubusercontent.com/65287945/133934268-50764b6a-f05e-4a08-9241-d4e0c26a0fb0.jpg)
![pronotetools4](https://user-images.githubusercontent.com/65287945/133934269-47959c23-a801-488c-b5a2-2c75bcf7e786.jpg)
![pronotetools5](https://user-images.githubusercontent.com/65287945/133934270-02345967-52b4-447a-a3ae-86178d25f0b0.jpg)
![pronotetools1](https://user-images.githubusercontent.com/65287945/133934271-295ce53c-e79c-4a4c-a1f4-35421156bb39.jpg)
![pronotetools2](https://user-images.githubusercontent.com/65287945/133934272-d8a566ff-c81f-4b78-9aad-bcdf044925e9.jpg)

**Comment by DocSystem** [comment]
Bonjour,
Cela est dû à la nouvelle version de Pronote, les éléments ayant changé,
Pour le moment, je vous conseille d'utiliser Dark Reader pour le dark mode !

Désolé

**Comment by jd-develop** [comment]
OK, je vais suivre votre conseil.
Merci !
